hawkw/sharded-slab

- .github/workflows/ci.yml
- benches/bench.rs
- src/lib.rs
- src/page/mod.rs
- src/page/slot.rs
- src/page/stack.rs
- src/tests.rs
- src/tid.rs
This change moves all the per-slot shared state (generation, ref count, 
and removal state) into a single `AtomicUsize`. This has several 
advantages:
* It reduces the overall complexity of the `Slot` type, as it no longer
depends on the complex interactions of multiple atomics. The loom
tests are now _much_ faster (which is also a nice sign of relative 
complexity, IMO), and the code is easier to reason about.
* All interactions with the generation will now involve a RMW. Even
when the generation is not being modified, we will always perform a
read-modify-write with that generation to update _some_ part of the
state (such as the ref count or removal state). If this RMW fails
because our view of the generation is stale, we'll re-acquire the 
state, and see that the generation has changed. …
> perf: consolidate per-slot state into one AtomicUsize

- Cargo.toml
- src/lib.rs
- src/page/mod.rs
- src/page/slot.rs
- src/page/stack.rs
- src/tests.rs
This fixes an issue where, when a slot is freed immediately by a call to
`remove` while uncontended, it was not added to the page's free list,
and thus never reused. This resulted in a memory leak.
I've also refactored some internals.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
>  fix: `remove` not adding slots to free lists 

- src/cfg.rs
- src/lib.rs
- src/page/slot.rs
- src/tests.rs
* fix: incorrect wrapping when overflowing maximum ref count
Currently, when the maximum reference count for a slot is reached, the
reference count wraps to 0. This is wrong, as it could potentially cause
a use-after-free by allowing the slot to be released while there are
still active references.
This commit fixes this by adding a check in `Slot::get` that creating a
new reference would not overflow the reference count. If the reference
count would overflow, `get` returns `None` instead. Additionally, I've
added debug assertions that ensure this check works correctly.
I've also added a new test for this.
Fixes #22
* feat(Config): validate concurrent refs
This commit adds a check in `Config::validate` that there can be at
least 2 concurrent references to a slot. Otherwise...what's the …
> improve reference count validation

- src/lib.rs
- src/page/slot.rs
- src/sync.rs
* feat(Slab::take): add exponential backoff when spinning
`Slab::take` will spin if there are currently outstanding references to
the `take`n slot. Spinning is not the ideal way to block a thread until
a state changes, since it uses CPU time that might be used by other
threads, and impacts power consumption. However, waiting "properly"
(e.g. with a condvar) here is difficult. If we wanted to give each slot
a `Mutex` and `Condvar` pair, we would need two heap allocations per
slot (assuming POSIX `pthread_mutex` and `pthread_cond`), plus 16 bytes
for the Rust `std::sync::Mutex` and `std::sync::Condvar` types. This is
a lot of additional per-slot overhead.
As a compromise, this commit updates `take` to spin with an exponential
backoff. Now, every time `take` spins, it will issue an …
> Improve spinning in `Slot::take`

- src/clear.rs
- src/lib.rs
- src/pool/mod.rs
Add type level documentation for `Pool`. Update exports to include `clear::Clear` and clean them up.
> docs(Pool): Add documentation for `Pool`

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- bin/loom.sh
- src/lib.rs
- src/page/mod.rs
- src/page/slot.rs
- src/page/stack.rs
- src/sync.rs
This branch updates `loom`to 0.3, adds a shell script (`bin/loom.sh`), 
which runs Loom tests with default values for Loom's configuration
variables, and makes a few minor CI tweaks to improve performance
by installing smaller Rust toolchains.
The nightly Rust compiler is used to enable Loom's location tracking
support. This allows Loom to emit diagnostics that include the caller's
source code locations when errors occur. For example, after modifying
the code to cause an invalid concurrent mutable access, we get nice
panics like this:
```
---- pool::tests::concurrent_create_clear stdout ----
================== Iteration 1 ==================
~~~~~~~~ THREAD 1 ~~~~~~~~
thread 'pool::tests::concurrent_create_clear' panicked at '
Causality violation: Concurrent write accesses to `UnsafeCell`. …
```
> test: update loom, CI improvements

- README.md
- src/lib.rs
This commit adds a brief summary of the `Pool` and `Slab` APIs, the
differences between them, and the use-cases for which they're
appropriate. I've added this both to the README and to the `lib.rs`
docs.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
> docs(Pool): add top-level docs on `Pool` vs `Slab`

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
<a name="0.0.9"></a>
* **Config:**  validate concurrent refs ([9b32af58](9b32af58), closes [#21](21))
* **Pool:**
*  add `fmt::Debug` impl for `Pool` ([ffa5c7a0](ffa5c7a0))
*  add `Default` impl for `Pool` ([d2399365](d2399365))
*  add a sharded object pool for reusing heap allocations (#19) ([89734508](89734508), closes [#2](2), [#15](15))
* **Slab::take:**  add exponential backoff when spinning ([6b743a27](6b743a27))
*   incorrect wrapping when overflowing maximum ref count ([aea693f3](aea693f3), closes [#22](22))
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
> chore: prepare to release 0.0.9

- src/iter.rs
- src/lib.rs
- src/page/slot.rs
- src/pool.rs
- src/shard.rs
- src/sync.rs
- src/tests/loom_slab.rs
Currently, creating a new `Slab` allocates a shards array of `Shard`
structs. The `Shard` struct itself owns two boxed arrays of local and
shared metadata for each page on that shard. Even though we don't
allocate the actual storage arrays for those pages until they are
needed, allocating the shard metadata eagerly means that a completely
empty slab results in a fairly large memory allocation up front. This is
especially the case when used with the default `Config`, which (on
64-bit machines) allows up to 4096 threads. On a 64-bit machine, the
`Shared` page metadata is 4 words, so 32 bytes, and the `Local` metadata
is another word. 33 bytes * 32 pages per shard = 1056 bytes, which is a
little over 1kb per shard. This means that the default config eagerly
allocates 4096 shards * 1056 bytes …
> fix: allocate shard metadata lazily

- Cargo.toml
- src/sync.rs
- src/tid.rs
I'm not sure this doesn't muck up the way you use loom, but it would be nice if loom was listed as a dev-dependency (as it is in tokio) so that its dependencies don't end up being in downstream Cargo.lock files.
(Upgraded proptest too since I happened to notice it and the upgrade seemed trivial anyway.)
> Make loom a dev-dependency (and upgrade proptest)

- Cargo.toml
This just updates the `loom` and `proptest` dependencies
to the latest releases. No API changes in these.
> chore: update test dependencies

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
*   make debug assertions drop safe ([26d35a69](https://github.com/hawkw/sharded-slab/commit/26d35a695c9e5d7c62ab07cc5e66a0c6f8b6eade))
*   improve panics on thread ID bit exhaustion ([9ecb8e61](https://github.com/hawkw/sharded-slab/commit/9ecb8e614f107f68b5c6ba770342ae72af1cd07b))
> chore: prepare to release v0.1.2

- .github/workflows/ci.yml
- src/sync.rs
> Set up MSRV in CI

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
*   set up MSRV in CI (#61) ([dfcc9080](https://github.com/hawkw/sharded-slab/commit/dfcc9080a62d08e359f298a9ffb0f275928b83e4), closes [#60](https://github.com/hawkw/sharded-slab/issues/60))
* **tests:**  duplicate `hint` mod defs with loom ([0ce3fd91](https://github.com/hawkw/sharded-slab/commit/0ce3fd91feac8b4edb4f1ece6aebfc4ba4e50026))
> chore: prepare to release v0.1.3

- src/page/slot.rs
- src/tests/custom_config.rs
- src/tests/loom_slab.rs
- src/tests/mod.rs
Hi, I used the following config and found the incorrect calculations of the generation and reference counter. After debugging, I  discovered that sometimes `Generation::pack` is used instead of `LifecycleGen::pack`, which can be fixed by this PR.
My config:
```rust
struct SlabConfig;
impl sharded_slab::Config for SlabConfig {
const INITIAL_PAGE_SIZE: usize = 32;
const MAX_PAGES: usize = 15;
const MAX_THREADS: usize = 256;
const RESERVED_BITS: usize = 24;
}
```
The bug cannot be reproduced with the default config, because `Generation` and `LifecycleGen` have the same `Pack::SHIFT`.
It would be nice to remove `impl Pack for Generation` in favor of different `impl Pack for KeyGen` and `impl Pack for LifecycleGen`, but I decided not to do any extra refactoring, which you may not accept.
If …
> fix(Slab): invalid generation in case of custom config

- .github/workflows/ci.yml
- src/tests/custom_config.rs
This commit changes the 32-bit CI builds to use a musl toolchain rather than glibc, so that CI can stop complaining that there's no 32-bit glibc.
> chore(CI): use musl for 32-bit builds

- Cargo.toml
- tests/reserved_bits_leak.rs
This commit adds an integration test reproducing #83.
I ran this test before and after the changes from PR #80, and I can
confirm that the test fails without the changes from #80, but passes
after #80. So, this means that #80 fixed the issue described in #83!
Fixes #80
> test: add a test reproducing #83

- src/iter.rs
- src/lib.rs
This type is returned by a public method, but it isn't publicly re-exported. This means that it cannot currently be named in downstream code, and the documentation for its `Iterator` implementation is not rendered in RustDoc. This is an oversight on my part, as the type was intended to be public.
This commit fixes that, by publicly re-exporting `UniqueIter`. In addition, I've added some improved documentation for `UniqueIter`, which should help users to understand its guarantees.
Fixes #77
> feat: publicly export `UniqueIter`

- .github/workflows/ci.yml
- Cargo.toml
- benches/bench.rs
- src/iter.rs
- src/lib.rs
- src/page/mod.rs
- src/page/slot.rs
- src/shard.rs
- src/tests/custom_config.rs
- src/tests/mod.rs
- src/tests/properties.rs
- src/tid.rs
I've written some ~~fuzzing~~ property based tests for public API. Fortunately (or not), it's found only simple bugs with boundary checks (caught in staging, the reason why I've decided to check the slab in such a way).
* Add fuzzing tests for public API
* Fix #73 (`unique_iter`)
* Fix panics in `get()` for some keys
* Satisfy [clippy](https://rust-lang.github.io/rust-clippy/master/index.html#incorrect_clone_impl_on_copy_type)
P.S. "fuzzing" is not an entirely valid name here. Initially, It checked only the absence of panics, so naming was more appropriate. Then, more properties were added. Would you happen to have any ideas on how to call it now?
> Fix bugs in get() and co + property based tests

- .github/workflows/ci.yml
This way, we can use that as the required check for merging PRs, so we
don't have to depend on a bunch of stuff in the GitHub branch protection
settings. This means that the required checks are defined in the CI
config file, rather than in the UI, and if we change job names
or add new checks, we can add them to the requirements in `ci.yml`
instead of the repo settings.
> more CI embetterments

- Cargo.toml
On current main (`ee45b4cfa79408fc46893a67f2d3005f79e4e04c`) with Rust 1.83 (`rustc 1.83.0 (90b35a623 2024-11-26)`, `cargo 1.83.0 (5ffbef321 2024-10-29)`), running `cargo check` gives this warning:
```
warning: unused manifest key: package.ignore
```
Note: this warning may be buried under other warnings that could be fixed by #102.
hawkw committed the `ignore = ["flake.nix", "flake.lock", ...]` key in 90bf2e92db1546eb7c1819da38fc741117b1a4a8 in 2023. I cannot find any reference online to there being an `ignore` key in Cargo manifests, and fram context I am guessing that this was intended to be `exclude`, which is documentd [here](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields).
This PR fixes the warning by changing the key to `exclude`.
> chore: Fix "unused manifest key: package.ignore"

- Cargo.toml
On current main(`ee45b4cfa79408fc46893a67f2d3005f79e4e04c`) with Rust 1.83 (`rustc 1.83.0 (90b35a623 2024-11-26)`, `cargo 1.83.0 (5ffbef321 2024-10-29)`), running `cargo check` gives many warnings, almost all of which are duplicates of these two:
```
warning: unexpected `cfg` condition name: `slab_print`
--> src/macros.rs:3:31
|
3   |         if cfg!(test) && cfg!(slab_print) {
|                               ^^^^^^^^^^
|
::: src/lib.rs:967:9
|
967 |         test_println!("drop OwnedEntry: try clearing data");
|         --------------------------------------------------- in this macro invocation
|
= help: consider using a Cargo feature instead
= help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = …
```
> chore: Fix "unexpected `cfg` condition name"

- src/lib.rs
- src/pool.rs
Even with #102 and #103 merged into current main (ee45b4cfa79408fc46893a67f2d3005f79e4e04c), with Rust 1.83 (`rustc 1.83.0 (90b35a623 2024-11-26)`, `cargo 1.83.0 (5ffbef321 2024-10-29)`), running `cargo clippy --all-targets --all-features` gives 16 lifetime-related lint warnings:
<details><summary>Warnings</summary>
```
warning: the following explicit lifetimes could be elided: 'a
--> src/pool.rs:873:6
|
873 | impl<'a, T, C> Ref<'a, T, C>
|      ^^            ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: `#[warn(clippy::needless_lifetimes)]` on by default
help: elide the lifetimes
|
873 - impl<'a, T, C> Ref<'a, T, C>
873 + impl<T, C> Ref<'_, T, C>
|
warning: the following explicit lifetimes could be elided: …
```
> chore: Clippy autofix

- src/lib.rs
Closes #69
As noted in #69, all hyperlinks to `slab` or `Slab` in the lib.rs top-level doc comment link to https://crates.io/crates/loom. This seems to be result of 2 errors dating back to the initial commit, relating to this code:
```rs
//! - [`slab`]: Carl Lerche's `slab` crate provides a slab implementation with a
//!   similar API, implemented by storing all data in a single vector.
...
//! [`slab`]: https://crates.io/crates/loom
```
There seems to be 2 problems with this:
1. The markdown is set up to link `slab` to https://crates.io/crates/loom instead of https://crates.io/crates/slab. There is another part of the doc comment containing `//! [`loom`]: https://crates.io/crates/loom`, so I assume this was a copy-paste error.
2. The markdown is set up to link _all_ occurrences of `slab` …
> chore(docs): Fix docs links
